name: CI/CD

# main 브랜치에 코드가 push 될 때 실행
on:
  push:
    branches:
      - "step3"

env:
  KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 지정한 저장소(현재 REPO)에서 코드를 워크플로우 환경으로 가져오도록 하는 github action
      - name: Checkout code
        uses: actions/checkout@v3

      # Java를 설정하는 github action
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      # 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootjar -x test

